### ping

GET http://localhost:8888/ping

### stop

GET http://localhost:8888/stop

### dispatch

POST http://localhost:8888/dispatch
content-type: application/json

{
  "topic": "foo",
  "message": "bar"
}