CREATE TABLE dept
(
    deptno INTEGER,
    dname  VARCHAR(14),
    loc    VARCHAR(13),
    PRIMARY KEY (deptno)
);

INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (30, 'SALES', 'CHICAGO');


-- change